#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRM")]
	public partial class TicketsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTickets(Tickets instance);
    partial void UpdateTickets(Tickets instance);
    partial void DeleteTickets(Tickets instance);
    #endregion
		
		public TicketsDataContext() : 
				base(global::WindowsFormsApp5.Properties.Settings.Default.CRMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TicketsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tickets> Tickets
		{
			get
			{
				return this.GetTable<Tickets>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tickets")]
	public partial class Tickets : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ticket_Id;
		
		private string _Kategori;
		
		private string _Baslik;
		
		private string _Oncelik;
		
		private System.Nullable<System.DateTime> _Baslangic;
		
		private System.Nullable<System.DateTime> _Bitirme;
		
		private System.Nullable<int> _Bekleme;
		
		private System.Nullable<int> _Durum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTicket_IdChanging(int value);
    partial void OnTicket_IdChanged();
    partial void OnKategoriChanging(string value);
    partial void OnKategoriChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnOncelikChanging(string value);
    partial void OnOncelikChanged();
    partial void OnBaslangicChanging(System.Nullable<System.DateTime> value);
    partial void OnBaslangicChanged();
    partial void OnBitirmeChanging(System.Nullable<System.DateTime> value);
    partial void OnBitirmeChanged();
    partial void OnBeklemeChanging(System.Nullable<int> value);
    partial void OnBeklemeChanged();
    partial void OnDurumChanging(System.Nullable<int> value);
    partial void OnDurumChanged();
    #endregion
		
		public Tickets()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticket_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ticket_Id
		{
			get
			{
				return this._Ticket_Id;
			}
			set
			{
				if ((this._Ticket_Id != value))
				{
					this.OnTicket_IdChanging(value);
					this.SendPropertyChanging();
					this._Ticket_Id = value;
					this.SendPropertyChanged("Ticket_Id");
					this.OnTicket_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori", DbType="NVarChar(MAX)")]
		public string Kategori
		{
			get
			{
				return this._Kategori;
			}
			set
			{
				if ((this._Kategori != value))
				{
					this.OnKategoriChanging(value);
					this.SendPropertyChanging();
					this._Kategori = value;
					this.SendPropertyChanged("Kategori");
					this.OnKategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="NVarChar(MAX)")]
		public string Baslik
		{
			get
			{
				return this._Baslik;
			}
			set
			{
				if ((this._Baslik != value))
				{
					this.OnBaslikChanging(value);
					this.SendPropertyChanging();
					this._Baslik = value;
					this.SendPropertyChanged("Baslik");
					this.OnBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oncelik", DbType="NVarChar(50)")]
		public string Oncelik
		{
			get
			{
				return this._Oncelik;
			}
			set
			{
				if ((this._Oncelik != value))
				{
					this.OnOncelikChanging(value);
					this.SendPropertyChanging();
					this._Oncelik = value;
					this.SendPropertyChanged("Oncelik");
					this.OnOncelikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslangic", DbType="Date")]
		public System.Nullable<System.DateTime> Baslangic
		{
			get
			{
				return this._Baslangic;
			}
			set
			{
				if ((this._Baslangic != value))
				{
					this.OnBaslangicChanging(value);
					this.SendPropertyChanging();
					this._Baslangic = value;
					this.SendPropertyChanged("Baslangic");
					this.OnBaslangicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bitirme", DbType="Date")]
		public System.Nullable<System.DateTime> Bitirme
		{
			get
			{
				return this._Bitirme;
			}
			set
			{
				if ((this._Bitirme != value))
				{
					this.OnBitirmeChanging(value);
					this.SendPropertyChanging();
					this._Bitirme = value;
					this.SendPropertyChanged("Bitirme");
					this.OnBitirmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bekleme", DbType="Int")]
		public System.Nullable<int> Bekleme
		{
			get
			{
				return this._Bekleme;
			}
			set
			{
				if ((this._Bekleme != value))
				{
					this.OnBeklemeChanging(value);
					this.SendPropertyChanging();
					this._Bekleme = value;
					this.SendPropertyChanged("Bekleme");
					this.OnBeklemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="Int")]
		public System.Nullable<int> Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
